#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Core Devices LLC
#
# Build a self-contained PebbleOS SDK bundle for a target (os, arch).
#
# Output: dist/pebbleos-sdk-<version>-<os>-<arch>.tar.gz containing all
# component archives plus an install.sh and pinned versions.sh.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

# shellcheck source=lib/common.sh
. "${SCRIPT_DIR}/lib/common.sh"
# shellcheck source=lib/platform.sh
. "${SCRIPT_DIR}/lib/platform.sh"
# shellcheck source=../versions.sh
. "${ROOT_DIR}/versions.sh"

usage() {
    cat <<EOF
Usage: $(basename "$0") [--os <linux|darwin>] [--arch <x86_64|aarch64>] [--out <dir>] [--cache-dir <dir>]

Builds dist/pebbleos-sdk-<version>-<os>-<arch>.tar.gz.

Options:
  --os ARG          Target OS (default: host OS)
  --arch ARG        Target architecture (default: host arch)
  --out DIR         Output directory (default: ${ROOT_DIR}/dist)
  --cache-dir DIR   Cache downloaded component archives in DIR (reuse on
                    rebuild). Cache is keyed by archive basename.
  -h, --help        Show this help
EOF
}

OS=""; ARCH=""; OUT_DIR="${ROOT_DIR}/dist"; CACHE_DIR=""
while [ $# -gt 0 ]; do
    case "$1" in
        --os)        OS="$2"; shift 2 ;;
        --arch)      ARCH="$2"; shift 2 ;;
        --out)       OUT_DIR="$2"; shift 2 ;;
        --cache-dir) CACHE_DIR="$2"; shift 2 ;;
        -h|--help)   usage; exit 0 ;;
        *) die "unknown argument: $1" ;;
    esac
done
[ -n "${CACHE_DIR}" ] && mkdir -p "${CACHE_DIR}"

OS="${OS:-$(detect_os)}"
ARCH="${ARCH:-$(detect_arch)}"
case "${OS}" in linux|darwin) ;; *) die "unsupported os: ${OS}" ;; esac
case "${ARCH}" in x86_64|aarch64) ;; *) die "unsupported arch: ${ARCH}" ;; esac

require_cmd tar
mkdir -p "${OUT_DIR}"

STAGE_DIR="$(mktemp -d)"
trap 'rm -rf "${STAGE_DIR}"' EXIT

BUNDLE_NAME="pebbleos-sdk-${SDK_VERSION}-${OS}-${ARCH}"
BUNDLE_ROOT="${STAGE_DIR}/${BUNDLE_NAME}"
mkdir -p "${BUNDLE_ROOT}/components"

log_info "Building bundle: ${BUNDLE_NAME}"

# Fetch each component archive (reusing the cache when available).
# Only `name` and `url_fn` are needed here — `dest_subdir` and `strip`
# are used by install.sh, not the builder.
while IFS=: read -r name url_fn _ _; do
    [ -n "${name}" ] || continue
    url="$("${url_fn}" "${OS}" "${ARCH}")" \
        || die "no URL configured for ${name} on ${OS}/${ARCH}"
    filename="$(basename "${url}")"
    out="${BUNDLE_ROOT}/components/${filename}"
    if [ -n "${CACHE_DIR}" ] && [ -f "${CACHE_DIR}/${filename}" ]; then
        log_info "Using cached ${name}: ${CACHE_DIR}/${filename}"
        cp "${CACHE_DIR}/${filename}" "${out}"
    else
        log_info "Downloading ${name}: ${url}"
        download_to "${url}" "${out}"
        if [ -n "${CACHE_DIR}" ]; then
            cp "${out}" "${CACHE_DIR}/${filename}"
        fi
    fi
    log_ok "ready $(basename "${out}") ($(wc -c < "${out}" | awk '{print $1}') bytes)"
done < <(sdk_components)

# Embed manifest, install script, and pinned versions.
cp "${ROOT_DIR}/versions.sh" "${BUNDLE_ROOT}/versions.sh"
cp "${ROOT_DIR}/scripts/install.sh" "${BUNDLE_ROOT}/install.sh"
cp "${ROOT_DIR}/scripts/lib/common.sh" "${BUNDLE_ROOT}/common.sh"
cp "${ROOT_DIR}/scripts/lib/platform.sh" "${BUNDLE_ROOT}/platform.sh"
chmod +x "${BUNDLE_ROOT}/install.sh"

# Persist target metadata for the embedded installer.
cat > "${BUNDLE_ROOT}/manifest.sh" <<EOF
# Auto-generated by build-bundle.sh — do not edit by hand.
BUNDLE_OS="${OS}"
BUNDLE_ARCH="${ARCH}"
BUNDLE_SDK_VERSION="${SDK_VERSION}"
EOF

# Pack.
TARBALL="${OUT_DIR}/${BUNDLE_NAME}.tar.gz"
log_info "Creating ${TARBALL}"
tar --create --gzip --file "${TARBALL}" --directory "${STAGE_DIR}" "${BUNDLE_NAME}"

# Generate sha256.
if command -v shasum >/dev/null 2>&1; then
    (cd "${OUT_DIR}" && shasum -a 256 "${BUNDLE_NAME}.tar.gz" > "${BUNDLE_NAME}.tar.gz.sha256")
elif command -v sha256sum >/dev/null 2>&1; then
    (cd "${OUT_DIR}" && sha256sum "${BUNDLE_NAME}.tar.gz" > "${BUNDLE_NAME}.tar.gz.sha256")
fi

log_ok "Bundle ready: ${TARBALL}"
